# Generated by Django 5.0.2 on 2024-02-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="is_client",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
    ]
