# Generated by Django 5.0.2 on 2024-02-19 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_usermodel_is_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="is_seller",
            field=models.BooleanField(default=False, verbose_name="Shope owner"),
        ),
    ]
