# Generated by Django 5.0.2 on 2024-02-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_cartitem_color_cartitem_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="color",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="size",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
