# Generated by Django 5.0.2 on 2024-02-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_orderitem_color_orderitem_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="statement_image",
            field=models.ImageField(default=1, upload_to="media/statement_image/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
