# Generated by Django 5.0.2 on 2024-02-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_order_address_payment_statement_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),
        migrations.AddField(
            model_name="order",
            name="post_office",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="tel",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
