# Generated by Django 5.0.2 on 2024-02-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_category_image_alter_cartitem_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="branch",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="district",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="province",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_company",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="statement_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/statement_image/"
            ),
        ),
    ]
