# Generated by Django 5.0.2 on 2024-02-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_order_branch_order_district_order_province_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
